(* 星座を表す型 *)
type seiza_t = Capricorus	(* 山羊座 *)
             | Aquarius		(* 水瓶座 *)
             | Pisces		(* 魚座 *)
             | Aries		(* 牡羊座 *)
             | Taurus		(* 牡牛座 *)
             | Gemini		(* 双子座 *)
             | Cancer		(* 蟹座 *)
             | Leo		(* 獅子座 *)
             | Virgo		(* 乙女座 *)
             | Libra		(* 天秤座 *)
             | Scorpius		(* 蠍座 *)
             | Sagittarius	(* 射手座 *)
